// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package store

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// An enum for the type of operations that the replication queue can process.
const (
	Ticket = iota
	Activate
	Deactivate
	Assign
)

// Every change to the state of the tickets in om-core is modelled as a StateUpdate.
type StateUpdate struct {
	Cmd    int      // The operation this update contains
	Key    string   // The key to update (or first key when Keys is populated)
	Keys   []string // Optional batch of keys for packed Activate/Deactivate updates
	Value  string   // The value to associate with this key (if applicable)
	ReplId string   // The replication ID assigned to this update by the state storage implementation
}

// PrimaryKey returns the primary ticket key identified by this update:
//   - For single-ticket updates (or packed updates that already set Key), it returns u.Key.
//   - For packed Activate/Deactivate updates where u.Key was left blank and ticket IDs
//     were only provided in u.Keys, it returns the first non-empty element of u.Keys.
//   - If u is nil or contains no non-empty ticket key, it returns "".
//
// This is primarily used when constructing an error StateResponse for a failed
// StateUpdate: StateResponse.Result is overloaded to carry the newly assigned
// replication ID on success (Err == nil), but on failure (Err != nil) it carries
// the ticket key of the StateUpdate that failed so callers of batched SendUpdates
// can attribute the error to the originating ticket.
func (u *StateUpdate) PrimaryKey() string {
	if u == nil {
		return ""
	}
	if u.Key != "" {
		return u.Key
	}
	for _, k := range u.Keys {
		if k != "" {
			return k
		}
	}
	return ""
}

// ParseReplIdTimestampMs extracts the millisecond timestamp from a replication ID
// formatted as "<timestamp_ms>-<seq>".
func ParseReplIdTimestampMs(replId string) (int64, error) {
	parts := strings.Split(replId, "-")
	if len(parts) == 0 || parts[0] == "" {
		return 0, fmt.Errorf("invalid replication ID %q", replId)
	}
	ts, err := strconv.ParseInt(parts[0], 10, 64)
	if err != nil {
		return 0, fmt.Errorf("invalid replication ID %q: %w", replId, err)
	}
	return ts, nil
}

func parseReplId(replId string) (int64, int64, bool) {
	parts := strings.Split(replId, "-")
	if len(parts) != 2 {
		return 0, 0, false
	}
	ts, err := strconv.ParseInt(parts[0], 10, 64)
	if err != nil {
		return 0, 0, false
	}
	seq, err := strconv.ParseInt(parts[1], 10, 64)
	if err != nil {
		return 0, 0, false
	}
	return ts, seq, true
}

// CompareReplIds compares two replication IDs formatted as "<timestamp_ms>-<seq>" numerically.
func CompareReplIds(a, b string) int {
	if a == b {
		return 0
	}
	if a == "" {
		return -1
	}
	if b == "" {
		return 1
	}
	tsA, seqA, okA := parseReplId(a)
	tsB, seqB, okB := parseReplId(b)
	if !okA || !okB {
		return strings.Compare(a, b)
	}
	if tsA < tsB {
		return -1
	}
	if tsA > tsB {
		return 1
	}
	if seqA < seqB {
		return -1
	}
	if seqA > seqB {
		return 1
	}
	return 0
}

// Results of changes to the state of the cache. State replication batches
// updates as much as possible, and every update generates a StateResponse that
// can be sent back to the underlying caller (since it may get batched with
// unrelated updates generated by RPC calls that happen concurrently). This is
// primarily used as the mechanism to send back a response from a CreateTicket
// call - this is how that call receives the ticket ID from the state storage
// layer. It may also used in internal implementations to track which updates
// have been applied to the local replicated ticket cache.
//
// Note that the Result field is overloaded depending on whether Err is nil:
//   - If Err is nil, Result contains the replication ID assigned to the update
//     by the state storage implementation (e.g., a Redis stream entry ID).
//   - If Err is not nil, Result contains the primary ticket key of the
//     StateUpdate that failed (via StateUpdate.PrimaryKey), used by the calling
//     function to identify which ticket request caused the error.
type StateResponse struct {
	Result string
	Err    error
}

// The core gRPC server instantiates a replicatedTicketCache on startup, and specifies
// how it wants to replicate om-core state by instantiating a StateReplicator
// that conforms to this interface.
type StateReplicator interface {
	GetUpdates() []*StateUpdate
	SendUpdates([]*StateUpdate) []*StateResponse
	GetReplIdValidator() *regexp.Regexp
}
